# 기본 Suricata 이미지 사용
FROM jasonish/suricata:latest

COPY docker/suricata/suricata.yaml /etc/suricata/suricata.yaml
COPY docker/suricata/suricata.rules /var/lib/suricata/rules/suricata.rules


USER root
